# Makefile

# defaults
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_INCLUDE_DIRS += $(PWD)/../../src/

VERILOG_SOURCES += $(PWD)/../../src/cordic_slice.v
VERILOG_SOURCES += $(PWD)/../../src/cordic_iterative.v
# use VHDL_SOURCES for VHDL files

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
TOPLEVEL = cordic_iterative

# MODULE is the basename of the Python test file
MODULE = cosim_cordic_iterative

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
