sin: clean
	make -f makefile.sin

slice: clean
	make -f makefile.slice

iterative: clean
	make -f makefile.iterative

wave: clean
	make -f makefile.wave

tt: clean
	make -f makefile.tt

clean:
	rm -r -f sim_build
	rm -f results.xml
