# Makefile

# defaults
SIM ?= icarus

WAVES = 1

TOPLEVEL_LANG ?= verilog

VERILOG_INCLUDE_DIRS += $(PWD)/../../src/

VERILOG_SOURCES = $(PWD)/../../src/spi_master_only_tx_single_cs.v

# use VHDL_SOURCES for VHDL files

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
TOPLEVEL = spi_master_only_tx_single_cs

# MODULE is the basename of the Python test file
MODULE = test_spi_master_only_tx_single_cs

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim