# Makefile

# defaults
SIM ?= icarus

WAVES = 1

TOPLEVEL_LANG ?= verilog

VERILOG_INCLUDE_DIRS += $(PWD)/../../src/

VERILOG_SOURCES = $(PWD)/../../src/wave_generator.v

# use VHDL_SOURCES for VHDL files

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
TOPLEVEL = wave_generator

# MODULE is the basename of the Python test file
MODULE = cosim_wave_generator

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim